---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: congratulations
  labels:
    app.kubernetes.io/name: congratulations
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: congratulations
  template:
    metadata:
      labels:
        app.kubernetes.io/name: congratulations
    spec:
      containers:
        - name: congratulations
          image: congratulations
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
